name: Manual Deploy and site publishing

on:
  workflow_dispatch:
    inputs:
      java-version:
        description: 'Java version'
        required: true
        default: '21'
        validation:
          pattern: '^(8|11|17|21)$'
          error: 'Must be one of: 8, 11, 17, 21'

jobs:
  deploy:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Cache local Maven repository
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-21-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-21
    - name: Deploy with Maven
      run: mvn -B deploy -DskipTests
    - name: Maven Site
      run: mvn -B site site:stage scm-publish:publish-scm
